# Generated by Django 5.2 on 2025-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_post_liked_by_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('LD', 'Landscape'), ('UB', 'Urban'), ('MC', 'Macro'), ('AS', 'Artisctic')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
