# Generated by Django 5.2 on 2025-04-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_post_category_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('NC', 'NoneCategory'), ('LD', 'Landscape'), ('UB', 'Urban'), ('MC', 'Macro'), ('AS', 'Artisctic')], default='Landscape', max_length=12),
        ),
    ]
